name: bsl
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

isar_version: &isar_version 3.1.0+1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  async: ^2.11.0
  intl: ^0.18.1
  sprintf: ^7.0.0
  cupertino_icons: ^1.0.6
  flutter_gen: ^5.3.2
  freezed: ^2.4.6
  # 权限
  permission_handler: ^11.1.0
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # 设备信息
  device_info_plus: ^9.1.1
  package_info_plus: ^5.0.1
  # 消息通知
  flutter_local_notifications: ^16.2.0
  # 外链跳转
  url_launcher: ^6.2.2
  # 存储
  simple_saver:
    git: https://github.com/pye52/simple_saver.git
  # 腾讯云
  tencentcloud_cos_sdk_plugin: ^1.0.9
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  isar: *isar_version
  isar_flutter_libs: *isar_version
  # 日志
  talker: ^3.2.0
  talker_dio_logger: ^2.4.0
  talker_flutter: ^3.6.0
  # 图片选择
  image_picker: ^1.0.5
  wechat_assets_picker: ^9.0.0-dev.2
  # 推送
  getuiflut: ^0.2.25
  # 录音
  record: ^4.4.4
  # 视频播放
  video_player: ^2.8.1
  # 音频播放
  audioplayers: ^5.2.1
  # 工具
  chinese_number: ^1.0.1
  # 友盟数据收集
  umeng_common_sdk: ^1.2.7

  # splash
  flutter_native_splash: ^2.3.8

  # 网络框架
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # 状态管理
  get: ^4.6.6
  mobx: ^2.2.3+1
  mobx_codegen: ^2.4.1
  flutter_mobx: ^2.2.0+1

  # 事件总线
  event_bus: ^2.0.0

  # 微信支付
  fluwx: ^4.4.9

  # html渲染
  flutter_widget_from_html: ^0.14.9

  # webview
  webview_flutter: ^4.4.2

  # 截图
  screenshot: ^2.1.0
  # 图片
  qr_flutter: ^4.1.0
  photo_view: ^0.14.0
  photo_manager: ^3.0.0-dev.5
  extended_image: ^8.2.0
  extended_image_library: ^4.0.2
  cached_network_image: ^3.3.0

  # ui组件
  nil: ^1.1.1
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  timelines: ^0.1.0
  msh_checkbox: ^2.0.1
  dropdown_button2: ^2.3.9
  paper_transition:
    git: https://gitee.com/dango/paper_transition.git
  audio_video_progress_bar: ^2.0.1
  flutter_inset_box_shadow: ^1.0.8
  signature: ^5.4.1
  syncfusion_flutter_signaturepad: ^24.1.41
  fluttertoast: ^8.2.4
  flutter_smart_dialog: ^4.9.5+2
  loading_animation_widget: ^1.2.0+4
  badges: ^3.1.2
  dotted_line: ^3.2.2
  dotted_border: ^2.1.0
  marquee: ^2.2.3
  easy_refresh: ^3.3.3+1
  table_calendar: ^3.0.9
  scrollable_positioned_list: ^0.3.8
  flutter_staggered_grid_view: ^0.7.0
  extended_tabs: ^4.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

  isar_generator: *isar_version
  retrofit_generator: ^8.0.6
  freezed_annotation: ^2.4.1
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  json_serializable: ^6.7.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
